In [1]:
import numpy as np
import scipy.linalg as sla

 Exercício 1.1 Classifique os sistemas abaixo com relação a quantidade e existência de
soluções.

In [2]:
def rank(A):
    return np.linalg.matrix_rank(A)

def classify(A, b):
    n = A.shape[1]
    Ã = np.c_[A, b]
    same_rank = rank(A) == rank(Ã)
    
    if same_rank and rank(A) == n:
        #print("Sistema Possível Determinado")
        return "Possui penas 1 solução"
    elif same_rank and rank(A) < n:
        #print("Sistema Possível Indeterminado")
        return "Possui infinitas soluções"
    elif rank(A) < rank(Ã):
        #print("Sistema Possível Indeterminado")
        return "Existe solução apenas aproximada"
    else: return "This was not supossed to happen !!!"

a)

x + 2y + 3z = 1

4x + 5y + 6z = 1

7x + 8y + 9z = 1

In [3]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([1, 1, 1])
print(classify(A, b))

Possui infinitas soluções


b)

2x + 3y = 10

−4x − 6y = −10

In [4]:
A = np.array([[2, 3], [-4, -6]])
b = np.array([10, -10])
print(classify(A, b))

Existe solução apenas aproximada


 Exercício 1.2 Repita o exemplo 3.2 acima, porém fazendo cada passo da execução de
forma explícita, comparando como o algoritmo 1.2 e a função sist_lin_tri_sup funcionam.
Sugestão: faça isso de forma manuscrita. Ajudará a entender melhor cada passo.

In [5]:
def sistLinTriSup(A, b):
    n = len(b)
    x = np.empty(n)
    x[n - 1] = b[n - 1]/A[n - 1, n - 1]
    
    print("A =\n", A, "\nb =", b)
    
    print("x[{}] = b[{}] / A[{}, {}]".format(n - 1, n - 1, n - 1, n - 1))
    print("x[{}] = {} / {}".format(n - 1, b[n - 1], A[n - 1, n - 1]))
    print("x[{}] = {}".format(n - 1, x[n - 1]))
    
    for i in range(n - 2, -1, -1):
        subA, subX, aii, bi = A[i, i + 1:], x[i + 1:], A[i, i], b[i]
        prod = subA * subX
        sm = np.sum(prod)
        sub = bi - sm
        div = sub / aii
        #print("x[i] = ( b[i] - np.sum( A[i, i + 1:] * x[i + 1:] ) ) / str(A[i, i])")
        print("x[{}] = ( b[{}] - np.sum( A[{}, {}:] * x[{}:] ) ) / A[{}, {}]".format(i, i, i, i + 1, i + 1, i, i))
        print("x[{}] = ( {} - np.sum( {} * {} ) ) / {}".format(i, bi, np.array2string(subA), np.array2string(subX), aii))
        print("x[{}] = ( {} - np.sum( {} ) ) / {}".format(i, bi, np.array2string(prod), aii))
        print("x[{}] = ( {} - {} ) / {}".format(i, bi, sm, aii))
        print("x[{}] = {} / {}".format(i, sub, aii))
        print("x[{}] = {}".format(i, div))
        x[i] = ( b[i] - np.sum( A[i, i + 1:] * x[i + 1:] ) ) / A[i, i]
        
    return x

In [6]:
A = np.array([[3, 4, -5, 1], [0, 1, 1, -2], [0, 0, 4, -5], [0, 0, 0, 2]])
b = np.array([-10, -1, 3, 2])
x = sistLinTriSup(A, b)

print("x =", x)
print("b =", b)
print("A.dot(x) == b, ", A.dot(x) == b)

A =
 [[ 3  4 -5  1]
 [ 0  1  1 -2]
 [ 0  0  4 -5]
 [ 0  0  0  2]] ,
b = [-10  -1   3   2]
x[3] = b[3] / A[3, 3]
x[3] = 2 / 2
x[3] = 1.0
x[2] = ( b[2] - np.sum( A[2, 3:] * x[3:] ) ) / A[2, 2]
x[2] = ( 3 - np.sum( [-5] * [1.] ) ) / 4
x[2] = ( 3 - np.sum( [-5.] ) ) / 4
x[2] = ( 3 - -5.0 ) / 4
x[2] = 8.0 / 4
x[2] = 2.0
x[1] = ( b[1] - np.sum( A[1, 2:] * x[2:] ) ) / A[1, 1]
x[1] = ( -1 - np.sum( [ 1 -2] * [2. 1.] ) ) / 1
x[1] = ( -1 - np.sum( [ 2. -2.] ) ) / 1
x[1] = ( -1 - 0.0 ) / 1
x[1] = -1.0 / 1
x[1] = -1.0
x[0] = ( b[0] - np.sum( A[0, 1:] * x[1:] ) ) / A[0, 0]
x[0] = ( -10 - np.sum( [ 4 -5  1] * [-1.  2.  1.] ) ) / 3
x[0] = ( -10 - np.sum( [ -4. -10.   1.] ) ) / 3
x[0] = ( -10 - -13.0 ) / 3
x[0] = 3.0 / 3
x[0] = 1.0
x = [ 1. -1.  2.  1.]
b = [-10  -1   3   2]
A.dot(x) == b,  [ True  True  True  True]


 Exercício 1.3 Repita o exemplo 3.3 acima, porém fazendo cada passo da execução de forma
explícita, comparando como o algoritmo 1.3 e a função sist_lin_tri_inf funcionam. Use
a mesma sugestão do exercício anterior.

 Exercício 1.4 Implemente uma função, cujos parâmetros de entrada sejam somente a matriz
de coeficientes e o vetor de termos independentes e que calcule o vetor solução para qualquer
um dos casos triviais vistos aqui. Atente para o fato de que a própria função terá de verificar se
a matriz de coeficientes é diagonal, triangular superior ou inferior e não o usuário.