In [1]:
import numpy as np

 Exercício 1.1 Classifique os sistemas abaixo com relação a quantidade e existência de
soluções.

In [2]:
def rank(A):
    return np.linalg.matrix_rank(A)

def classify(A, b):
    n = A.shape[1]
    Ã = np.c_[A, b]
    same_rank = rank(A) == rank(Ã)
    
    if same_rank and rank(A) == n:
        #print("Sistema Possível Determinado")
        return "Possui penas 1 solução"
    elif same_rank and rank(A) < n:
        #print("Sistema Possível Indeterminado")
        return "Possui infinitas soluções"
    elif rank(A) < rank(Ã):
        #print("Sistema Possível Indeterminado")
        return "Existe solução apenas aproximada"
    else: return "This was not supossed to happen !!!"

a)

x + 2y + 3z = 1

4x + 5y + 6z = 1

7x + 8y + 9z = 1

In [3]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([1, 1, 1])
print(classify(A, b))

Possui infinitas soluções


b)

2x + 3y = 10

−4x − 6y = −10

In [4]:
A = np.array([[2, 3], [-4, -6]])
b = np.array([10, -10])
print(classify(A, b))

Existe solução apenas aproximada


 Exercício 1.2 Repita o exemplo 3.2 acima, porém fazendo cada passo da execução de
forma explícita, comparando como o algoritmo 1.2 e a função sist_lin_tri_sup funcionam.
Sugestão: faça isso de forma manuscrita. Ajudará a entender melhor cada passo.

In [5]:
def uppTriLinSys(A, b, prt=False):    
    n = m = len(b)
    x = np.empty(n)
    x[n - 1] = b[n - 1] / A[n - 1, n - 1]
    
    if prt:
        print("A =\n", A, "\nb =", b, "\n")
        print("ALGORÍTMO")
        print("Passo 2: calcular a incógnita de maior índice")
        print("xn = bn / amn")
        print("x{} = b{} / a{}{}".format(n, n, m, n))
        print("OBS: apartir daqui em relação a 'CÓDIGO', só muda os índeces dentro dos []")
        print("x[{}] = b[{}] / a[{}, {}]".format(n, n, m, n))
        print("x[{}] = {} / {}".format(n, b[n - 1], A[n - 1, n - 1]))
        print("x[{}] = {}".format(n, x[n - 1]))
        print("CÓDIGO")
        print("x[{}] = b[{}] / A[{}, {}]".format(n - 1, n - 1, m - 1, n - 1))
        print("x[{}] = {} / {}".format(n - 1, b[n - 1], A[n - 1, n - 1]))
        print("x[{}] = {}".format(n - 1, x[n - 1]))
    
    for i in range(n - 2, -1, -1):
        x[i] = ( b[i] - np.sum( A[i, i + 1:] * x[i + 1:] ) ) / A[i, i]
        
        if prt:
            subA, subX, aii, bi = A[i, i + 1:], x[i + 1:], A[i, i], b[i]
            prod = subA * subX
            sm = np.sum(prod)
            sub = bi - sm
            div = sub / aii
            print("\nALGORÍTMO")
            print("Passo 3: calcular os valores restantes do vetor solução")
            print("xi = ( bi - (somatorio aijxj de j=i+1 até n) ) / aii")
            print("x{} = ( b{} - (somatorio a{}{}X{} de {} até {}) ) / a{}{}".format(i+1, i+1, i+1, i+2, i+2, i+2, n, i+1, i+1))
            print("aij == a{}{} == ai,(j:n) == ai,(i+1:n) == a[{}, {}:]".format(i+1, i+2, i+1, i+2))
            print("xj == x{} == x(j:n) == x(i+1:n) == x[{}:]".format(i+2, i+2))
            print("x[{}] = ( b[{}] - (somatorio a[{}, {}:]x[{}:] de {} até {}) ) / a[{}, {}]".
                  format(i+1, i+1, i+1, i+2, i+2, i+2, n, i+1, i+1))
            print("x[{}] = ( {} - somatorio( {}{} ) ) / {}"
                  .format(i+1, bi, np.array2string(subA), np.array2string(subX), aii))
            print("x[{}] = ( {} - somatorio{} ) / {}".format(i+1, bi, np.array2string(prod), aii))
            print("x[{}] = ( {} - {} ) / {}".format(i+1, bi, sm, aii))
            print("x[{}] = {} / {}".format(i+1, sub, aii))
            print("x[{}] = {}".format(i+1, div))
            print("CÓDIGO")
            print("x[{}] = ( b[{}] - np.sum( A[{}, {}:] * x[{}:] ) ) / A[{}, {}]".format(i, i, i, i + 1, i + 1, i, i))
            print("x[{}] = ( {} - np.sum( {} * {} ) ) / {}".format(i, bi, np.array2string(subA), np.array2string(subX), aii))
            print("x[{}] = ( {} - np.sum( {} ) ) / {}".format(i, bi, np.array2string(prod), aii))
            print("x[{}] = ( {} - {} ) / {}".format(i, bi, sm, aii))
            print("x[{}] = {} / {}".format(i, sub, aii))
            print("x[{}] = {}".format(i, div))
            
    return x

In [6]:
A = np.array([[3, 4, -5, 1], [0, 1, 1, -2], [0, 0, 4, -5], [0, 0, 0, 2]])
b = np.array([-10, -1, 3, 2])
x = uppTriLinSys(A, b, True)

print("\nRESULTADOS")
print("x =", x)
print("b =", b)
print("A.dot(x) == b, ", A.dot(x) == b)

A =
 [[ 3  4 -5  1]
 [ 0  1  1 -2]
 [ 0  0  4 -5]
 [ 0  0  0  2]] 
b = [-10  -1   3   2] 

ALGORÍTMO
Passo 2: calcular a incógnita de maior índice
xn = bn / amn
x4 = b4 / a44
OBS: apartir daqui em relação a 'CÓDIGO', só muda os índeces dentro dos []
x[4] = b[4] / a[4, 4]
x[4] = 2 / 2
x[4] = 1.0
CÓDIGO
x[3] = b[3] / A[3, 3]
x[3] = 2 / 2
x[3] = 1.0

ALGORÍTMO
Passo 3: calcular os valores restantes do vetor solução
xi = ( bi - (somatorio aijxj de j=i+1 até n) ) / aii
x3 = ( b3 - (somatorio a34X4 de 4 até 4) ) / a33
aij == a34 == ai,(j:n) == ai,(i+1:n) == a[3, 4:]
xj == x4 == x(j:n) == x(i+1:n) == x[4:]
x[3] = ( b[3] - (somatorio a[3, 4:]x[4:] de 4 até 4) ) / a[3, 3]
x[3] = ( 3 - somatorio( [-5][1.] ) ) / 4
x[3] = ( 3 - somatorio[-5.] ) / 4
x[3] = ( 3 - -5.0 ) / 4
x[3] = 8.0 / 4
x[3] = 2.0
CÓDIGO
x[2] = ( b[2] - np.sum( A[2, 3:] * x[3:] ) ) / A[2, 2]
x[2] = ( 3 - np.sum( [-5] * [1.] ) ) / 4
x[2] = ( 3 - np.sum( [-5.] ) ) / 4
x[2] = ( 3 - -5.0 ) / 4
x[2] = 8.0 / 4
x[2] = 2.0

ALGORÍTMO
Pass

 Exercício 1.3 Repita o exemplo 3.3 acima, porém fazendo cada passo da execução de forma
explícita, comparando como o algoritmo 1.3 e a função sist_lin_tri_inf funcionam. Use
a mesma sugestão do exercício anterior.

In [7]:
def lowTriLinSys(A, b, prt=False):
    n = m = len(b)
    x = np.empty(n)
    x[0] = b[0] / A[0, 0]
    
    if prt:
        print("A =\n", A, "\nb =", b, "\n")
        print("ALGORÍTMO")
        print("Passo 2: calcular a incógnita de menor índice")
        print("x1 = b1 / a11")
        print("OBS: apartir daqui em relação a 'CÓDIGO', só muda os índeces dentro dos []")
        print("x[{}] = b[{}] / a[{}, {}]".format(1, 1, 1, 1))
        print("x[{}] = {} / {}".format(1, b[0], A[0, 0]))
        print("x[{}] = {}".format(1, x[0]))
        print("CÓDIGO")
        print("x[{}] = b[{}] / A[{}, {}]".format(0, 0, 0, 0))
        print("x[{}] = {} / {}".format(0, b[0], A[0, 0]))
        print("x[{}] = {}".format(0, x[0]))
    
    for i in range(1, n):
        x[i] = ( b[i] - np.sum( A[i, :i] * x[:i] ) ) / A[i, i]
        
        if prt:
            subA, subX, aii, bi = A[i, :i], x[:i], A[i, i], b[i]
            prod = subA * subX
            sm = np.sum(prod)
            sub = bi - sm
            div = sub / aii
            print("\nALGORÍTMO")
            print("Passo 3: calcular os valores do vetor solução")
            print("xi = ( bi - (somatorio aijxj de j=1 até i - 1) ) / aii")
            print("x{} = ( b{} - (somatorio a{}{}X{} de 1 até {}) ) / a{}{}".format(i+1, i+1, i+1, i, i, i, i+1, i+1))
            print("aij == a{}{} == ai,(j:i-1) == ai,(1:i-1) == a[{}, :{}]".format(i+1, i, i+1, i))
            print("xj == x{} == x(j:i-1) == x(1:i-1) == x[:{}]".format(i, i))
            print("x[{}] = ( b[{}] - (somatorio a[{}, :{}]x[:{}] de 1 até {}) ) / a[{}, {}]".
                  format(i+1, i+1, i+1, i, i, i, i+1, i+1))
            print("x[{}] = ( {} - somatorio( {}{} ) ) / {}"
                  .format(i+1, bi, np.array2string(subA), np.array2string(subX), aii))
            print("x[{}] = ( {} - somatorio{} ) / {}".format(i+1, bi, np.array2string(prod), aii))
            print("x[{}] = ( {} - {} ) / {}".format(i+1, bi, sm, aii))
            print("x[{}] = {} / {}".format(i+1, sub, aii))
            print("x[{}] = {}".format(i+1, div))
            print("CÓDIGO")
            print("x[{}] = ( b[{}] - np.sum( A[{}, :{}] * x[:{}] ) ) / A[{}, {}]".format(i, i, i, i+1, i+1, i, i))
            print("x[{}] = ( {} - np.sum( {} * {} ) ) / {}".format(i, bi, np.array2string(subA), np.array2string(subX), aii))
            print("x[{}] = ( {} - np.sum( {} ) ) / {}".format(i, bi, np.array2string(prod), aii))
            print("x[{}] = ( {} - {} ) / {}".format(i, bi, sm, aii))
            print("x[{}] = {} / {}".format(i, sub, aii))
            print("x[{}] = {}".format(i, div))
    return x

In [8]:
A = np.array([[3,0,0,0],[2,1,0,0],[1,0,1,0],[1,1,1,1]])
b = np.array([4,2,4,2])
x = lowTriLinSys(A, b, True)

print("\nRESULTADOS")
print("x =", x)
print("b =", b)
print("A.dot(x) == b, ", A.dot(x) == b)

A =
 [[3 0 0 0]
 [2 1 0 0]
 [1 0 1 0]
 [1 1 1 1]] 
b = [4 2 4 2] 

ALGORÍTMO
Passo 2: calcular a incógnita de menor índice
x1 = b1 / a11
OBS: apartir daqui em relação a 'CÓDIGO', só muda os índeces dentro dos []
x[1] = b[1] / a[1, 1]
x[1] = 4 / 3
x[1] = 1.3333333333333333
CÓDIGO
x[0] = b[0] / A[0, 0]
x[0] = 4 / 3
x[0] = 1.3333333333333333

ALGORÍTMO
Passo 3: calcular os valores do vetor solução
xi = ( bi - (somatorio aijxj de j=1 até i - 1) ) / aii
x2 = ( b2 - (somatorio a21X1 de 1 até 1) ) / a22
aij == a21 == ai,(j:i-1) == ai,(1:i-1) == a[2, :1]
xj == x1 == x(j:i-1) == x(1:i-1) == x[:1]
x[2] = ( b[2] - (somatorio a[2, :1]x[:1] de 1 até 1) ) / a[2, 2]
x[2] = ( 2 - somatorio( [2][1.33333333] ) ) / 1
x[2] = ( 2 - somatorio[2.66666667] ) / 1
x[2] = ( 2 - 2.6666666666666665 ) / 1
x[2] = -0.6666666666666665 / 1
x[2] = -0.6666666666666665
CÓDIGO
x[1] = ( b[1] - np.sum( A[1, :2] * x[:2] ) ) / A[1, 1]
x[1] = ( 2 - np.sum( [2] * [1.33333333] ) ) / 1
x[1] = ( 2 - np.sum( [2.66666667] ) ) / 1
x[1

 Exercício 1.4 Implemente uma função, cujos parâmetros de entrada sejam somente a matriz
de coeficientes e o vetor de termos independentes e que calcule o vetor solução para qualquer
um dos casos triviais vistos aqui. Atente para o fato de que a própria função terá de verificar se
a matriz de coeficientes é diagonal, triangular superior ou inferior e não o usuário.

In [9]:
# retorna qual dos 3 casos triviais a matriz se encaixa
def getMatTyp(A):
    m, n = A.shape # m == quantidade de linhas, n == quantidade de colunas   
    if (m != n): return "not quadratic"
    
    # {li indice linha, ci indice coluna} dos elementos que não são zero na matriz A
    # ou seja, A[li[i]][ci[i]] == 0 sempre, for i in range(len(li)), com len(li) == len(ci)
    li, ci = np.nonzero(A) 
    
    if False not in (li <= ci) and False not in (li >= ci):
        """
        https://www.preparaenem.com/matematica/matriz-triangular.htm
        "Seria possível uma mesma matriz ser simultaneamente triangular superior e triangular inferior? Sim! 
        Se forem nulos todos os elementos que não pertencem à diagonal principal, essa matriz será triangular superior e inferior. 
        Esse tipo de matriz recebe um nome especial, é chamada de matriz diagonal."
        """
        return "diagonal"
    
    elif False not in (li <= ci):
        """
        minha adaptação
        sendo (li <= ci) indices dos elementos apartir da digonal principal pra cima, se li <= ci nunca for False, 
        dentre os elementos apartir da diagonal principal pra cima há ao menos um elemento diferente de zero 
        e todos os elementos abaixo da diagonal principal são zero.
        """
        """
        https://www.preparaenem.com/matematica/matriz-triangular.htm
        "quando os elementos à esquerda e abaixo da diagonal principal forem nulos, teremos uma matriz triangular superior, 
        ou, simplesmente, se Aij = 0, para i > j"
        considerando sendo li[i] equivalente a i e ci[i] equivalente a j
        """
        return "upper triangular"
    elif False not in (li >= ci):
        """
        minha adaptação
        sendo (li >= ci) indices dos elementos apartir da digonal principal pra baixo, se li >= ci nunca for False, 
        dentre os elementos apartir da diagonal principal pra baixo há ao menos um elemento diferente de zero 
        e todos os elementos acima da diagonal principal são zero.
        """
        """
        https://www.preparaenem.com/matematica/matriz-triangular.htm
        "Observe que, nos elementos à direita e acima da diagonal principal, o número da linha é inferior ao número da coluna. 
        Quando esses elementos forem todos nulos, teremos uma matriz triangular inferior. 
        Simplificando, podemos dizer que, se Aij = 0, para i < j, há uma matriz triangular inferior."
        considerando sendo li[i] equivalente a i e ci[i] equivalente a j
        """
        return "lower triangular"
    else:
        return "not trivial case"

In [10]:
#casos de teste
mts = np.array([[3, 4, -5, 1], [0, 1, 1, -2], [0, 0, 4, -5], [0, 0, 0, 2]])
print(mts)
print(getMatTyp(mts))
mts = np.array([[3, 4, -5, 0], [0, 1, 1, -2], [0, 0, 4, -5], [1, 0, 0, 2]])
print(mts)
print(getMatTyp(mts))
mts = np.array([[0,0,0, 1], [0, 0,0,0], [0, 0, 0, 0], [0, 0, 0, 0]])
print(mts)
print(getMatTyp(mts))
mti = np.array([[3,0,0,0],[2,1,0,0],[1,0,1,0],[1,1,1,1]])
print(mti)
print(getMatTyp(mti))
mti = np.array([[3,0,0,1],[2,1,0,0],[1,0,1,0],[1,1,1,1]])
print(mti)
print(getMatTyp(mti))
md = np.array([[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]])
print(md)
print(getMatTyp(md))
md = np.array([[1,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]])
print(md)
print(getMatTyp(md))
md = np.array([[0,0,0,0],[0,1,0,0],[0,0,0,0],[0,0,0,0]])
print(md)
print(getMatTyp(md))
md = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])
print(md)
print(getMatTyp(md))
md = np.array([[0,1,2,3],[1,0,2,3],[1,2,0,3],[1,2,3,0]])
print(md)
print(getMatTyp(md))

[[ 3  4 -5  1]
 [ 0  1  1 -2]
 [ 0  0  4 -5]
 [ 0  0  0  2]]
upper triangular
[[ 3  4 -5  0]
 [ 0  1  1 -2]
 [ 0  0  4 -5]
 [ 1  0  0  2]]
not trivial case
[[0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
upper triangular
[[3 0 0 0]
 [2 1 0 0]
 [1 0 1 0]
 [1 1 1 1]]
lower triangular
[[3 0 0 1]
 [2 1 0 0]
 [1 0 1 0]
 [1 1 1 1]]
not trivial case
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
diagonal
[[1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
diagonal
[[0 0 0 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 0 0 0]]
diagonal
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
diagonal
[[0 1 2 3]
 [1 0 2 3]
 [1 2 0 3]
 [1 2 3 0]]
not trivial case


In [11]:
def diaLinSys(A, b): return b / A.diagonal()

def vecSolTriCas(A, b):
    triCas = getMatTyp(A)
    
    if triCas == "diagonal":
        return diaLinSys(A, b)
    elif triCas == "lower triangular":
        return lowTriLinSys(A, b)
    elif triCas == "upper triangular":
        return uppTriLinSys(A, b)
    else:
        print(triCas, "can't be solved")
        return -1

In [12]:
A = np.diag([1,4,2])
b = np.array([4, 2, 2])
vecSolTriCas(A, b)

array([4. , 0.5, 1. ])

In [13]:
A = np.array([[3,4,-5,1],[0,1,1,-2],[0,0,4,-5],[0,0,0,2]])
b = np.array([-10,-1,3,2])
vecSolTriCas(A, b)

array([ 1., -1.,  2.,  1.])

In [14]:
A = np.array([[3,0,0,0],[2,1,0,0],[1,0,1,0],[1,1,1,1]])
b = np.array([4,2,4,2])
vecSolTriCas(A, b)

array([ 1.33333333, -0.66666667,  2.66666667, -1.33333333])