In [1]:
import numpy as np
import scipy.linalg as sla

def printMat(A):
    for i in A:
        print(i)
    return

In [2]:
# método trivial para matriz triangular superior
def uppTriLinSys(A, b):    
    n = len(b)
    x = np.empty(n)
    
    x[n - 1] = b[n - 1] / A[n - 1, n - 1]
    for i in range(n - 2, -1, -1):
        x[i] = ( b[i] - np.sum( A[i, i + 1:] * x[i + 1:] ) ) / A[i, i]
            
    return x

def escalonamento(A, b):
    n = len(A)
    Ab = np.c_[A, b] # matriz extendida
    
    # escalonamento
    for c in range(n-1):
        # pivotamento parcial
        row_i_for_permutation = np.abs(Ab[c:, c]).argmax() + c
        Ab[[c, row_i_for_permutation]] = Ab[[row_i_for_permutation, c]] # swap(c, row_i_for_permutation)
        # pivotamento parcial
        for l in range(c+1, n):
            Ab[l] = Ab[l] - (Ab[l, c] / Ab[c, c]) * Ab[c]
    # escalonamento
    return Ab[:, :-1], Ab[:, -1]

# eliminação gaussiana com pivotamento parcial
def gausEliParPiv(A, b):
    esc = escalonamento(A, b)
    return uppTriLinSys(esc[0], esc[1])

(a)  
x1 + x2 + x3 = 1  
4x1 + 4x2 + 2x3 = 2  
2x1 + x2 − x3 = 0

In [4]:
A = [[1,1,1], [4,4,2], [2,1,-1]]
b = [1,2,0]
print(gausEliParPiv(A, b), '\n', sla.solve(A, b), '\n', gausEliParPiv(A, b) == sla.solve(A, b))

antes do escalonamento
A
[1, 1, 1]
[4, 4, 2]
[2, 1, -1]
b
1
2
0
após escalonamento 
 [[ 4  4  2]
 [ 0 -1 -2]
 [ 0  0  0]] [ 2 -1  0]


LinAlgError: Matrix is singular.

(b)  
7x1 − 7x2 + x3 = 1  
−3x1 + 3x2 + 2x3 = 2  
7x1 + 7x2 − 72x3 = 7

In [ ]:
A = [[7,7,-3], [-3,3,2], [7,7,-72]]
b = [1,2,7]
xo = sla.solve(A, b)
A, b = escalonamento(A, b)
xe = sla.solve(A, b)
print(A, b)
print(xo == xe)
print(xe)
#print(gausEliParPiv(A, b), '\n', sla.solve(A, b), '\n', gausEliParPiv(A, b) == sla.solve(A, b))

In [ ]:
A = [[7,7,-3], [-3,3,2], [7,7,-72]]
b = [1,2,7]
for i in range(len(b)):
    print(sum(A[i] * xe) == b[i])

(c)  
x1 + 2x2 + 3x3 + 4x4 = 20  
2x1 + 2x2 + 3x3 + 4x4 = 22  
3x1 + 3x2 + 3x3 + 4x4 = 22  
4x1 + 4x2 + 4x3 + 4x4 = 24

In [ ]:
A = [[1,2,3,4], [2,2,3,4], [3,3,3,4], [4,4,4,4]]
b = [20, 22, 22, 24]
xo = sla.solve(A, b)
A, b = escalonamento(A, b)
xe = sla.solve(A, b)
print(xo == xe)
print(xe)
#print(gausEliParPiv(A, b), '\n', sla.solve(A, b), '\n', gausEliParPiv(A, b) == sla.solve(A, b))

In [ ]:
A = [[1,2,3,4], [2,2,3,4], [3,3,3,4], [4,4,4,4]]
b = [20, 22, 22, 24]
for i in range(len(b)):
    print(sum(A[i] * xe) == b[i])