In [1]:
import numpy as np
import scipy.linalg as sla

In [2]:
A = np.array([[1,1,1], [4,4,2], [2,1,-1]])
A

array([[ 1,  1,  1],
       [ 4,  4,  2],
       [ 2,  1, -1]])

In [3]:
b = np.array([1,2,0])
b

array([1, 2, 0])

In [4]:
Ab = np.c_[A, b]
Ab

array([[ 1,  1,  1,  1],
       [ 4,  4,  2,  2],
       [ 2,  1, -1,  0]])

In [5]:
c = 0
l = 1
print('\n', Ab)
row_i_for_permutation = np.abs(Ab[c:, c]).argmax() + c
if abs(Ab[row_i_for_permutation, c]) > abs(Ab[c, c]):
    Ab[[c, row_i_for_permutation]] = Ab[[row_i_for_permutation, c]]
print('\n', Ab)
Ab[l] = Ab[l] - (Ab[l, c] / Ab[c, c]) * Ab[c]
print('\n', Ab)


 [[ 1  1  1  1]
 [ 4  4  2  2]
 [ 2  1 -1  0]]

 [[ 4  4  2  2]
 [ 1  1  1  1]
 [ 2  1 -1  0]]

 [[ 4  4  2  2]
 [ 0  0  0  0]
 [ 2  1 -1  0]]


In [6]:
c = 0
l = 2
print('\n', Ab)
row_i_for_permutation = np.abs(Ab[c:, c]).argmax() + c
if abs(Ab[row_i_for_permutation, c]) > abs(Ab[c, c]):
    Ab[[c, row_i_for_permutation]] = Ab[[row_i_for_permutation, c]]
print('\n', Ab)
Ab[l] = Ab[l] - (Ab[l, c] / Ab[c, c]) * Ab[c]
print('\n', Ab)


 [[ 4  4  2  2]
 [ 0  0  0  0]
 [ 2  1 -1  0]]

 [[ 4  4  2  2]
 [ 0  0  0  0]
 [ 2  1 -1  0]]

 [[ 4  4  2  2]
 [ 0  0  0  0]
 [ 0 -1 -2 -1]]


In [7]:
c = 1
l = 2
print('\n', Ab)
row_i_for_permutation = np.abs(Ab[c:, c]).argmax() + c
if abs(Ab[row_i_for_permutation, c]) > abs(Ab[c, c]):
    Ab[[c, row_i_for_permutation]] = Ab[[row_i_for_permutation, c]]
print('\n', Ab)
Ab[l] = Ab[l] - (Ab[l, c] / Ab[c, c]) * Ab[c]
print('\n', Ab)


 [[ 4  4  2  2]
 [ 0  0  0  0]
 [ 0 -1 -2 -1]]

 [[ 4  4  2  2]
 [ 0 -1 -2 -1]
 [ 0  0  0  0]]

 [[ 4  4  2  2]
 [ 0 -1 -2 -1]
 [ 0  0  0  0]]
