In [1]:
import numpy as np
import scipy.linalg as sla

In [2]:
# esqueci isso
def low(A):
    n = A.shape[0]
    for l in range(n):
        A[l, l] = 1
        A[l, l+1:] = np.array([0. for x in range(n - l - 1)])

In [3]:
A = np.array([[1,1,1], [4,4,2], [2,1,-1]])
A

array([[ 1,  1,  1],
       [ 4,  4,  2],
       [ 2,  1, -1]])

In [4]:
U = np.array(A, dtype=np.float128) 
n = U.shape[0]
L = np.identity(n)
P = np.identity(n)
P,L,U

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[ 1.,  1.,  1.],
        [ 4.,  4.,  2.],
        [ 2.,  1., -1.]], dtype=float128))

In [5]:
c = 0
row_i_for_permutation = np.abs(U[c:, c]).argmax() + c
if np.abs(U[row_i_for_permutation, c]) > np.abs(U[c, c]):
    U[[c, row_i_for_permutation]] = U[[row_i_for_permutation, c]] # swap(c, row_i_for_permutation)
    P[[c, row_i_for_permutation]] = P[[row_i_for_permutation, c]] # aqui a matriz de Pivotamento altera
    #L[[c, row_i_for_permutation]] = L[[row_i_for_permutation, c]]

P,L,U

(array([[0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[ 4.,  4.,  2.],
        [ 1.,  1.,  1.],
        [ 2.,  1., -1.]], dtype=float128))

In [6]:
l = 1
line,div,col = U[l],U[l,c]/U[c,c],U[c]
print("U[l] - (U[l, c] / U[c, c]) * U[c]")
print("U[{}] - (U[{}, {}] / U[{}, {}]) * U[{}]".format(l,l,c,c,c,c))
print("{} - ({} / {}) * {}".format(line, U[l, c], U[c, c], col))
print("{} - {} * {}".format(line, div, col))
print("{} - {}".format(line, div * col))
print("{}".format(line - div * col))
if not (l+1 > n-1):
    ll=l+1
else:
    ll = l % (n-1) + 1 + c
L[ll, c] = (U[l, c] / U[c, c]) # (1)
U[l] = U[l] - (U[l, c] * U[c]) / U[c, c]

P,L,U

U[l] - (U[l, c] / U[c, c]) * U[c]
U[1] - (U[1, 0] / U[0, 0]) * U[0]
[1. 1. 1.] - (1.0 / 4.0) * [4. 4. 2.]
[1. 1. 1.] - 0.25 * [4. 4. 2.]
[1. 1. 1.] - [1.  1.  0.5]
[0.  0.  0.5]


(array([[0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.]]),
 array([[1.  , 0.  , 0.  ],
        [0.  , 1.  , 0.  ],
        [0.25, 0.  , 1.  ]]),
 array([[ 4. ,  4. ,  2. ],
        [ 0. ,  0. ,  0.5],
        [ 2. ,  1. , -1. ]], dtype=float128))

In [7]:
l = 2
line,div,col = U[l],U[l,c]/U[c,c],U[c]
print("U[l] - (U[l, c] / U[c, c]) * U[c]")
print("U[{}] - (U[{}, {}] / U[{}, {}]) * U[{}]".format(l,l,c,c,c,c))
print("{} - ({} / {}) * {}".format(line, U[l, c], U[c, c], col))
print("{} - {} * {}".format(line, div, col))
print("{} - {}".format(line, div * col))
print("{}".format(line - div * col))
if not (l+1 > n-1):
    ll=l+1
else:
    ll = l % (n-1) + 1 + c
L[ll, c] = (U[l, c] / U[c, c]) # (1)
U[l] = U[l] - (U[l, c] * U[c]) / U[c, c]

P,L,U

U[l] - (U[l, c] / U[c, c]) * U[c]
U[2] - (U[2, 0] / U[0, 0]) * U[0]
[ 2.  1. -1.] - (2.0 / 4.0) * [4. 4. 2.]
[ 2.  1. -1.] - 0.5 * [4. 4. 2.]
[ 2.  1. -1.] - [2. 2. 1.]
[ 0. -1. -2.]


(array([[0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.]]),
 array([[1.  , 0.  , 0.  ],
        [0.5 , 1.  , 0.  ],
        [0.25, 0.  , 1.  ]]),
 array([[ 4. ,  4. ,  2. ],
        [ 0. ,  0. ,  0.5],
        [ 0. , -1. , -2. ]], dtype=float128))

In [8]:
c = 1
row_i_for_permutation = np.abs(U[c:, c]).argmax() + c
if np.abs(U[row_i_for_permutation, c]) > np.abs(U[c, c]):
    U[[c, row_i_for_permutation]] = U[[row_i_for_permutation, c]] # swap(c, row_i_for_permutation)
    P[[c, row_i_for_permutation]] = P[[row_i_for_permutation, c]] # aqui a matriz de Pivotamento altera
    #L[[c, row_i_for_permutation]] = L[[row_i_for_permutation, c]]

P,L,U

(array([[0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]]),
 array([[1.  , 0.  , 0.  ],
        [0.5 , 1.  , 0.  ],
        [0.25, 0.  , 1.  ]]),
 array([[ 4. ,  4. ,  2. ],
        [ 0. , -1. , -2. ],
        [ 0. ,  0. ,  0.5]], dtype=float128))

In [9]:
l = 2
line,div,col = U[l],U[l,c]/U[c,c],U[c]
print("U[l] - (U[l, c] / U[c, c]) * U[c]")
print("U[{}] - (U[{}, {}] / U[{}, {}]) * U[{}]".format(l,l,c,c,c,c))
print("{} - ({} / {}) * {}".format(line, U[l, c], U[c, c], col))
print("{} - {} * {}".format(line, div, col))
print("{} - {}".format(line, div * col))
print("{}".format(line - div * col))
if not (l+1 > n-1):
    ll=l+1
else:
    ll = l % (n-1) + 1 + c
L[ll, c] = (U[l, c] / U[c, c]) # (1)
U[l] = U[l] - (U[l, c] * U[c]) / U[c, c]

P,L,U

U[l] - (U[l, c] / U[c, c]) * U[c]
U[2] - (U[2, 1] / U[1, 1]) * U[1]
[0.  0.  0.5] - (0.0 / -1.0) * [ 0. -1. -2.]
[0.  0.  0.5] - -0.0 * [ 0. -1. -2.]
[0.  0.  0.5] - [-0.  0.  0.]
[0.  0.  0.5]


(array([[0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]]),
 array([[ 1.  ,  0.  ,  0.  ],
        [ 0.5 ,  1.  ,  0.  ],
        [ 0.25, -0.  ,  1.  ]]),
 array([[ 4. ,  4. ,  2. ],
        [ 0. , -1. , -2. ],
        [ 0. ,  0. ,  0.5]], dtype=float128))

In [10]:
sla.lu(A)

(array([[0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.]]),
 array([[ 1.  ,  0.  ,  0.  ],
        [ 0.5 ,  1.  ,  0.  ],
        [ 0.25, -0.  ,  1.  ]]),
 array([[ 4. ,  4. ,  2. ],
        [ 0. , -1. , -2. ],
        [ 0. ,  0. ,  0.5]]))