In [1]:
import numpy as np
import scipy.linalg as sla

In [2]:
A = np.array([[1,2,3,4], [2,2,3,4], [3,3,3,4], [4,4,4,4]])
A

array([[1, 2, 3, 4],
       [2, 2, 3, 4],
       [3, 3, 3, 4],
       [4, 4, 4, 4]])

In [4]:
U = np.array(A, dtype=np.float128) 
n = U.shape[0]
L = np.identity(n)
P = np.identity(n)
P,L,U

(array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]),
 array([[1., 2., 3., 4.],
        [2., 2., 3., 4.],
        [3., 3., 3., 4.],
        [4., 4., 4., 4.]], dtype=float128))

In [5]:
c = 0
row_i_for_permutation = np.abs(U[c:, c]).argmax() + c
if np.abs(U[row_i_for_permutation, c]) > np.abs(U[c, c]):
    U[[c, row_i_for_permutation]] = U[[row_i_for_permutation, c]] # swap(c, row_i_for_permutation)
    P[[c, row_i_for_permutation]] = P[[row_i_for_permutation, c]] # aqui a matriz de Pivotamento altera
    L[[c, row_i_for_permutation]] = L[[row_i_for_permutation, c]]

P,L,U

(array([[0., 0., 0., 1.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [1., 0., 0., 0.]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]),
 array([[4., 4., 4., 4.],
        [2., 2., 3., 4.],
        [3., 3., 3., 4.],
        [1., 2., 3., 4.]], dtype=float128))

In [6]:
l = 1
line,div,col = U[l],U[l,c]/U[c,c],U[c]
print("U[l] - (U[l, c] / U[c, c]) * U[c]")
print("U[{}] - (U[{}, {}] / U[{}, {}]) * U[{}]".format(l,l,c,c,c,c))
print("{} - ({} / {}) * {}".format(line, U[l, c], U[c, c], col))
print("{} - {} * {}".format(line, div, col))
print("{} - {}".format(line, div * col))
print("{}".format(line - div * col))
L[l, c] = (U[l, c] / U[c, c]) # (1)
U[l] = U[l] - U[l, c] * U[c] / U[c, c]

P,L,U

U[l] - (U[l, c] / U[c, c]) * U[c]
U[1] - (U[1, 0] / U[0, 0]) * U[0]
[2. 2. 3. 4.] - (2.0 / 4.0) * [4. 4. 4. 4.]
[2. 2. 3. 4.] - 0.5 * [4. 4. 4. 4.]
[2. 2. 3. 4.] - [2. 2. 2. 2.]
[0. 0. 1. 2.]


(array([[0., 0., 0., 1.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [1., 0., 0., 0.]]),
 array([[1. , 0. , 0. , 0. ],
        [0.5, 1. , 0. , 0. ],
        [0. , 0. , 1. , 0. ],
        [0. , 0. , 0. , 1. ]]),
 array([[4., 4., 4., 4.],
        [0., 0., 1., 2.],
        [3., 3., 3., 4.],
        [1., 2., 3., 4.]], dtype=float128))

In [7]:
l = 2
line,div,col = U[l],U[l,c]/U[c,c],U[c]
print("U[l] - (U[l, c] / U[c, c]) * U[c]")
print("U[{}] - (U[{}, {}] / U[{}, {}]) * U[{}]".format(l,l,c,c,c,c))
print("{} - ({} / {}) * {}".format(line, U[l, c], U[c, c], col))
print("{} - {} * {}".format(line, div, col))
print("{} - {}".format(line, div * col))
print("{}".format(line - div * col))
L[l, c] = (U[l, c] / U[c, c]) # (1)
U[l] = U[l] - U[l, c] * U[c] / U[c, c]

P,L,U

U[l] - (U[l, c] / U[c, c]) * U[c]
U[2] - (U[2, 0] / U[0, 0]) * U[0]
[3. 3. 3. 4.] - (3.0 / 4.0) * [4. 4. 4. 4.]
[3. 3. 3. 4.] - 0.75 * [4. 4. 4. 4.]
[3. 3. 3. 4.] - [3. 3. 3. 3.]
[0. 0. 0. 1.]


(array([[0., 0., 0., 1.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [1., 0., 0., 0.]]),
 array([[1.  , 0.  , 0.  , 0.  ],
        [0.5 , 1.  , 0.  , 0.  ],
        [0.75, 0.  , 1.  , 0.  ],
        [0.  , 0.  , 0.  , 1.  ]]),
 array([[4., 4., 4., 4.],
        [0., 0., 1., 2.],
        [0., 0., 0., 1.],
        [1., 2., 3., 4.]], dtype=float128))

In [8]:
l = 3
line,div,col = U[l],U[l,c]/U[c,c],U[c]
print("U[l] - (U[l, c] / U[c, c]) * U[c]")
print("U[{}] - (U[{}, {}] / U[{}, {}]) * U[{}]".format(l,l,c,c,c,c))
print("{} - ({} / {}) * {}".format(line, U[l, c], U[c, c], col))
print("{} - {} * {}".format(line, div, col))
print("{} - {}".format(line, div * col))
print("{}".format(line - div * col))
L[l, c] = (U[l, c] / U[c, c]) # (1)
U[l] = U[l] - U[l, c] * U[c] / U[c, c]

P,L,U

U[l] - (U[l, c] / U[c, c]) * U[c]
U[3] - (U[3, 0] / U[0, 0]) * U[0]
[1. 2. 3. 4.] - (1.0 / 4.0) * [4. 4. 4. 4.]
[1. 2. 3. 4.] - 0.25 * [4. 4. 4. 4.]
[1. 2. 3. 4.] - [1. 1. 1. 1.]
[0. 1. 2. 3.]


(array([[0., 0., 0., 1.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [1., 0., 0., 0.]]),
 array([[1.  , 0.  , 0.  , 0.  ],
        [0.5 , 1.  , 0.  , 0.  ],
        [0.75, 0.  , 1.  , 0.  ],
        [0.25, 0.  , 0.  , 1.  ]]),
 array([[4., 4., 4., 4.],
        [0., 0., 1., 2.],
        [0., 0., 0., 1.],
        [0., 1., 2., 3.]], dtype=float128))

In [9]:
c = 1
row_i_for_permutation = np.abs(U[c:, c]).argmax() + c
if np.abs(U[row_i_for_permutation, c]) > np.abs(U[c, c]):
    U[[c, row_i_for_permutation]] = U[[row_i_for_permutation, c]] # swap(c, row_i_for_permutation)
    P[[c, row_i_for_permutation]] = P[[row_i_for_permutation, c]] # aqui a matriz de Pivotamento altera
    L[[c, row_i_for_permutation]] = L[[row_i_for_permutation, c]]

P,L,U

(array([[0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.]]),
 array([[1.  , 0.  , 0.  , 0.  ],
        [0.5 , 1.  , 0.  , 0.  ],
        [0.75, 0.  , 1.  , 0.  ],
        [0.25, 0.  , 0.  , 1.  ]]),
 array([[4., 4., 4., 4.],
        [0., 1., 2., 3.],
        [0., 0., 0., 1.],
        [0., 0., 1., 2.]], dtype=float128))

In [10]:
l = 2
line,div,col = U[l],U[l,c]/U[c,c],U[c]
print("U[l] - (U[l, c] / U[c, c]) * U[c]")
print("U[{}] - (U[{}, {}] / U[{}, {}]) * U[{}]".format(l,l,c,c,c,c))
print("{} - ({} / {}) * {}".format(line, U[l, c], U[c, c], col))
print("{} - {} * {}".format(line, div, col))
print("{} - {}".format(line, div * col))
print("{}".format(line - div * col))
L[l, c] = (U[l, c] / U[c, c]) # (1)
U[l] = U[l] - U[l, c] * U[c] / U[c, c]

P,L,U

U[l] - (U[l, c] / U[c, c]) * U[c]
U[2] - (U[2, 1] / U[1, 1]) * U[1]
[0. 0. 0. 1.] - (0.0 / 1.0) * [0. 1. 2. 3.]
[0. 0. 0. 1.] - 0.0 * [0. 1. 2. 3.]
[0. 0. 0. 1.] - [0. 0. 0. 0.]
[0. 0. 0. 1.]


(array([[0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.]]),
 array([[1.  , 0.  , 0.  , 0.  ],
        [0.5 , 1.  , 0.  , 0.  ],
        [0.75, 0.  , 1.  , 0.  ],
        [0.25, 0.  , 0.  , 1.  ]]),
 array([[4., 4., 4., 4.],
        [0., 1., 2., 3.],
        [0., 0., 0., 1.],
        [0., 0., 1., 2.]], dtype=float128))

In [11]:
l = 3
line,div,col = U[l],U[l,c]/U[c,c],U[c]
print("U[l] - (U[l, c] / U[c, c]) * U[c]")
print("U[{}] - (U[{}, {}] / U[{}, {}]) * U[{}]".format(l,l,c,c,c,c))
print("{} - ({} / {}) * {}".format(line, U[l, c], U[c, c], col))
print("{} - {} * {}".format(line, div, col))
print("{} - {}".format(line, div * col))
print("{}".format(line - div * col))
L[l, c] = (U[l, c] / U[c, c]) # (1)
U[l] = U[l] - U[l, c] * U[c] / U[c, c]

P,L,U

U[l] - (U[l, c] / U[c, c]) * U[c]
U[3] - (U[3, 1] / U[1, 1]) * U[1]
[0. 0. 1. 2.] - (0.0 / 1.0) * [0. 1. 2. 3.]
[0. 0. 1. 2.] - 0.0 * [0. 1. 2. 3.]
[0. 0. 1. 2.] - [0. 0. 0. 0.]
[0. 0. 1. 2.]


(array([[0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.]]),
 array([[1.  , 0.  , 0.  , 0.  ],
        [0.5 , 1.  , 0.  , 0.  ],
        [0.75, 0.  , 1.  , 0.  ],
        [0.25, 0.  , 0.  , 1.  ]]),
 array([[4., 4., 4., 4.],
        [0., 1., 2., 3.],
        [0., 0., 0., 1.],
        [0., 0., 1., 2.]], dtype=float128))

In [12]:
c = 2
row_i_for_permutation = np.abs(U[c:, c]).argmax() + c
if np.abs(U[row_i_for_permutation, c]) > np.abs(U[c, c]):
    U[[c, row_i_for_permutation]] = U[[row_i_for_permutation, c]] # swap(c, row_i_for_permutation)
    P[[c, row_i_for_permutation]] = P[[row_i_for_permutation, c]] # aqui a matriz de Pivotamento altera
    L[[c, row_i_for_permutation]] = L[[row_i_for_permutation, c]]

P,L,U

(array([[0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]),
 array([[1.  , 0.  , 0.  , 0.  ],
        [0.5 , 1.  , 0.  , 0.  ],
        [0.75, 0.  , 1.  , 0.  ],
        [0.25, 0.  , 0.  , 1.  ]]),
 array([[4., 4., 4., 4.],
        [0., 1., 2., 3.],
        [0., 0., 1., 2.],
        [0., 0., 0., 1.]], dtype=float128))

In [13]:
l = 3
line,div,col = U[l],U[l,c]/U[c,c],U[c]
print("U[l] - (U[l, c] / U[c, c]) * U[c]")
print("U[{}] - (U[{}, {}] / U[{}, {}]) * U[{}]".format(l,l,c,c,c,c))
print("{} - ({} / {}) * {}".format(line, U[l, c], U[c, c], col))
print("{} - {} * {}".format(line, div, col))
print("{} - {}".format(line, div * col))
print("{}".format(line - div * col))
L[l, c] = (U[l, c] / U[c, c]) # (1)
U[l] = U[l] - U[l, c] * U[c] / U[c, c]

P,L,U

U[l] - (U[l, c] / U[c, c]) * U[c]
U[3] - (U[3, 2] / U[2, 2]) * U[2]
[0. 0. 0. 1.] - (0.0 / 1.0) * [0. 0. 1. 2.]
[0. 0. 0. 1.] - 0.0 * [0. 0. 1. 2.]
[0. 0. 0. 1.] - [0. 0. 0. 0.]
[0. 0. 0. 1.]


(array([[0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]),
 array([[1.  , 0.  , 0.  , 0.  ],
        [0.5 , 1.  , 0.  , 0.  ],
        [0.75, 0.  , 1.  , 0.  ],
        [0.25, 0.  , 0.  , 1.  ]]),
 array([[4., 4., 4., 4.],
        [0., 1., 2., 3.],
        [0., 0., 1., 2.],
        [0., 0., 0., 1.]], dtype=float128))

In [14]:
sla.lu(A)

(array([[0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.]]),
 array([[1.  , 0.  , 0.  , 0.  ],
        [0.25, 1.  , 0.  , 0.  ],
        [0.5 , 0.  , 1.  , 0.  ],
        [0.75, 0.  , 0.  , 1.  ]]),
 array([[4., 4., 4., 4.],
        [0., 1., 2., 3.],
        [0., 0., 1., 2.],
        [0., 0., 0., 1.]]))