In [1]:
import numpy as np
import scipy.linalg as sla

In [2]:
def lu_factor(A):
    """
        LU factorization with partial pivorting

        Overwrite A with: 
            U (upper triangular) and (unit Lower triangular) L 
        Return [LU,piv] 
            Where piv is 1d numpy array with row swap indices 
    """
    n = A.shape[0]
    piv = np.arange(0,n)
    for k in range(n-1):

        # piv
        max_row_index = np.argmax(abs(A[k:n,k])) + k
        piv[[k,max_row_index]] = piv[[max_row_index,k]]
        A[[k,max_row_index]] = A[[max_row_index,k]]

        # LU 
        for i in range(k+1,n):          
            A[i,k] = A[i,k]/A[k,k]      
            for j in range(k+1,n):      
                A[i,j] -= A[i,k]*A[k,j] 

    return A,piv

In [3]:
A = np.array([[1,1,1], [4,4,2], [2,1,-1]])
A

array([[ 1,  1,  1],
       [ 4,  4,  2],
       [ 2,  1, -1]])

In [4]:
U = np.array(A, dtype=np.float128) 
n = U.shape[0]
L = np.identity(n)
P = np.identity(n)
P,L,U

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[ 1.,  1.,  1.],
        [ 4.,  4.,  2.],
        [ 2.,  1., -1.]], dtype=float128))

In [5]:
c = 0
row_i_for_permutation = np.abs(U[c:, c]).argmax() + c
if np.abs(U[row_i_for_permutation, c]) > np.abs(U[c, c]):
    U[[c, row_i_for_permutation]] = U[[row_i_for_permutation, c]] # swap(c, row_i_for_permutation)
    P[[c, row_i_for_permutation]] = P[[row_i_for_permutation, c]] # aqui a matriz de Pivotamento altera
    # L[[c, row_i_for_permutation]] = L[[row_i_for_permutation, c]]

P,L,U

(array([[0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[ 4.,  4.,  2.],
        [ 1.,  1.,  1.],
        [ 2.,  1., -1.]], dtype=float128))

In [6]:
l = 1
line,div,col = U[l],U[l,c]/U[c,c],U[c]
print("U[l] - (U[l, c] / U[c, c]) * U[c]")
print("U[{}] - (U[{}, {}] / U[{}, {}]) * U[{}]".format(l,l,c,c,c,c))
print("{} - ({} / {}) * {}".format(line, U[l, c], U[c, c], col))
print("{} - {} * {}".format(line, div, col))
print("{} - {}".format(line, div * col))
print("{}".format(line - div * col))
L[l, c] = (U[l, c] / U[c, c]) # (1)
U[l] = U[l] - (U[l, c] * U[c]) / U[c, c]

P,L,U

U[l] - (U[l, c] / U[c, c]) * U[c]
U[1] - (U[1, 0] / U[0, 0]) * U[0]
[1. 1. 1.] - (1.0 / 4.0) * [4. 4. 2.]
[1. 1. 1.] - 0.25 * [4. 4. 2.]
[1. 1. 1.] - [1.  1.  0.5]
[0.  0.  0.5]


(array([[0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.]]),
 array([[1.  , 0.  , 0.  ],
        [0.25, 1.  , 0.  ],
        [0.  , 0.  , 1.  ]]),
 array([[ 4. ,  4. ,  2. ],
        [ 0. ,  0. ,  0.5],
        [ 2. ,  1. , -1. ]], dtype=float128))

In [7]:
l = 2
line,div,col = U[l],U[l,c]/U[c,c],U[c]
print("U[l] - (U[l, c] / U[c, c]) * U[c]")
print("U[{}] - (U[{}, {}] / U[{}, {}]) * U[{}]".format(l,l,c,c,c,c))
print("{} - ({} / {}) * {}".format(line, U[l, c], U[c, c], col))
print("{} - {} * {}".format(line, div, col))
print("{} - {}".format(line, div * col))
print("{}".format(line - div * col))
L[l, c] = (U[l, c] / U[c, c]) # (1)
U[l] = U[l] - (U[l, c] * U[c]) / U[c, c]

P,L,U

U[l] - (U[l, c] / U[c, c]) * U[c]
U[2] - (U[2, 0] / U[0, 0]) * U[0]
[ 2.  1. -1.] - (2.0 / 4.0) * [4. 4. 2.]
[ 2.  1. -1.] - 0.5 * [4. 4. 2.]
[ 2.  1. -1.] - [2. 2. 1.]
[ 0. -1. -2.]


(array([[0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.]]),
 array([[1.  , 0.  , 0.  ],
        [0.25, 1.  , 0.  ],
        [0.5 , 0.  , 1.  ]]),
 array([[ 4. ,  4. ,  2. ],
        [ 0. ,  0. ,  0.5],
        [ 0. , -1. , -2. ]], dtype=float128))

In [8]:
c = 1
row_i_for_permutation = np.abs(U[c:, c]).argmax() + c
if np.abs(U[row_i_for_permutation, c]) > np.abs(U[c, c]):
    U[[c, row_i_for_permutation]] = U[[row_i_for_permutation, c]] # swap(c, row_i_for_permutation)
    P[[c, row_i_for_permutation]] = P[[row_i_for_permutation, c]] # aqui a matriz de Pivotamento altera
    # L[[c, row_i_for_permutation]] = L[[row_i_for_permutation, c]]

P,L,U

(array([[0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]]),
 array([[1.  , 0.  , 0.  ],
        [0.25, 1.  , 0.  ],
        [0.5 , 0.  , 1.  ]]),
 array([[ 4. ,  4. ,  2. ],
        [ 0. , -1. , -2. ],
        [ 0. ,  0. ,  0.5]], dtype=float128))

In [9]:
l = 2
line,div,col = U[l],U[l,c]/U[c,c],U[c]
print("U[l] - (U[l, c] / U[c, c]) * U[c]")
print("U[{}] - (U[{}, {}] / U[{}, {}]) * U[{}]".format(l,l,c,c,c,c))
print("{} - ({} / {}) * {}".format(line, U[l, c], U[c, c], col))
print("{} - {} * {}".format(line, div, col))
print("{} - {}".format(line, div * col))
print("{}".format(line - div * col))
L[l, c] = (U[l, c] / U[c, c]) # (1)
U[l] = U[l] - (U[l, c] * U[c]) / U[c, c]

P,L,U

U[l] - (U[l, c] / U[c, c]) * U[c]
U[2] - (U[2, 1] / U[1, 1]) * U[1]
[0.  0.  0.5] - (0.0 / -1.0) * [ 0. -1. -2.]
[0.  0.  0.5] - -0.0 * [ 0. -1. -2.]
[0.  0.  0.5] - [-0.  0.  0.]
[0.  0.  0.5]


(array([[0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]]),
 array([[ 1.  ,  0.  ,  0.  ],
        [ 0.25,  1.  ,  0.  ],
        [ 0.5 , -0.  ,  1.  ]]),
 array([[ 4. ,  4. ,  2. ],
        [ 0. , -1. , -2. ],
        [ 0. ,  0. ,  0.5]], dtype=float128))

In [10]:
sla.lu(A)

(array([[0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.]]),
 array([[ 1.  ,  0.  ,  0.  ],
        [ 0.5 ,  1.  ,  0.  ],
        [ 0.25, -0.  ,  1.  ]]),
 array([[ 4. ,  4. ,  2. ],
        [ 0. , -1. , -2. ],
        [ 0. ,  0. ,  0.5]]))

In [11]:
lu_factor(A)

(array([[ 4,  4,  2],
        [ 0,  1,  1],
        [ 0,  1, -2]]),
 array([1, 0, 2]))

In [12]:
A

array([[ 4,  4,  2],
       [ 0,  1,  1],
       [ 0,  1, -2]])

In [13]:
c = 0
A[c:, c]

array([4, 0, 0])

In [14]:
def f(l, n):
    if not (l + 1 > n-1):
        return l+1
    else:
        return l % (n-1) + 1

for l in range(1, 4):
    print("{} -> {}".format(l, f(l, 4)))

1 -> 2
2 -> 3
3 -> 1
